/************************************************************************
    AttendEase - A simple, point-and-click attendance program.
    Copyright (C) 2013-2014  James Wolff, Timothy Chandler, Sterling Long, Cole Howe

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*************************************************************************/

package attendease.gui;

import attendease.util.AFrame;
import attendease.util.FrameController;
import attendease.util.Group;
import attendease.util.Meeting;
import attendease.util.MiscUtils;
import attendease.util.Start;
import attendease.util.Student;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author timothy.chandler
 */
public class GroupGUI extends AFrame {

    /**
     * Creates new form GroupGUI
     */
    public GroupGUI() {
        preInit();
        initComponents();
//        postInit();
    }
    
    private void preInit(){
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Start.createLog(ex, "Unable to set proper look and feel");
        } catch (InstantiationException ex) {
            Start.createLog(ex, "Unable to set proper look and feel");
        } catch (IllegalAccessException ex) {
            Start.createLog(ex, "Unable to set proper look and feel");
        } catch (UnsupportedLookAndFeelException ex) {
            Start.createLog(ex, "Unable to set proper look and feel");
        }
        isEditing=false;
        oldName="";
    }
    
    
//    private void postInit(){
//        meetingIsHidden=false;
//        meetingTabPanel=new javax.swing.JPanel();
//        mep=new MeetingEditPanel();
//        meetingTab=mep.getMeetingTabbedPane();
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(meetingTabPanel);
//        meetingTabPanel.setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addComponent(meetingTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(0, 55, Short.MAX_VALUE))
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addGap(0, 0, 0)
//                .addComponent(meetingTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addContainerGap())
//        );
//        mainTabbedPane.addTab("Meeting", meetingTabPanel);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        mainTabbedPane = new javax.swing.JTabbedPane();
        groupTab = new javax.swing.JPanel();
        groupNameLabel = new javax.swing.JLabel();
        groupNameTextField = new javax.swing.JTextField();
        importLabel = new javax.swing.JLabel();
        locationTextField = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        infoLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        createButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Group Settings");
        setName("gg"); // NOI18N
        setResizable(false);

        mainPanel.setPreferredSize(new java.awt.Dimension(261, 384));

        mainTabbedPane.setPreferredSize(new java.awt.Dimension(261, 267));
        mainTabbedPane.setRequestFocusEnabled(false);

        groupTab.setPreferredSize(new java.awt.Dimension(260, 267));

        groupNameLabel.setText("Group Name:");

        groupNameTextField.setBackground(java.awt.Color.red);
        groupNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                groupNameTextFieldKeyReleased(evt);
            }
        });

        importLabel.setText("Import Students as Excel File");

        locationTextField.setEditable(false);
        locationTextField.setFocusable(false);

        browseButton.setText("Browse...");
        browseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                browseButtonMouseReleased(evt);
            }
        });

        infoLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        infoLabel.setText("Alphanumeric only (0-9a-zA-Z)");

        javax.swing.GroupLayout groupTabLayout = new javax.swing.GroupLayout(groupTab);
        groupTab.setLayout(groupTabLayout);
        groupTabLayout.setHorizontalGroup(
            groupTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(groupTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(groupNameTextField)
                    .addGroup(groupTabLayout.createSequentialGroup()
                        .addComponent(locationTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(browseButton))
                    .addGroup(groupTabLayout.createSequentialGroup()
                        .addGroup(groupTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(groupTabLayout.createSequentialGroup()
                                .addComponent(groupNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(infoLabel))
                            .addComponent(importLabel))
                        .addGap(0, 27, Short.MAX_VALUE)))
                .addContainerGap())
        );
        groupTabLayout.setVerticalGroup(
            groupTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(groupTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(groupNameLabel)
                    .addComponent(infoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(groupNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(importLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(groupTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseButton))
                .addContainerGap(252, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Group", groupTab);

        cancelButton.setText("Cancel");
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cancelButtonMouseReleased(evt);
            }
        });

        createButton.setText("Create");
        createButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                createButtonMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(createButton)
                        .addGap(89, 89, 89)
                        .addComponent(cancelButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(mainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(createButton))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE))
        );

        setJMenuBar(FrameController.getMf().getJMenuBar());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createButtonMouseReleased
        if(groupNameTextField.getText()!=null&&!groupNameTextField.getText().equals("")){
            if(groupNameTextField.getText().matches("[0-9a-zA-Z]+")){
                if(isEditing){
                    if(groupNameTextField.getText().toUpperCase().charAt(0)==groupNameTextField.getText().toLowerCase().charAt(0)){
                        javax.swing.JOptionPane.showMessageDialog(FrameController.getMf(), "The first character of the Group Name must be a letter. (A-Z, a-z)");
                        return;
                    }
                    Group temp=FrameController.removeGroup(oldName);
                    temp=new Group(temp.getIdentifier(),groupNameTextField.getText(),new ArrayList<Meeting>(),new ArrayList<Student>(), locationTextField.getText()+"", true);
                    FrameController.addGroup(temp);
                    FrameController.getGroup(groupNameTextField.getText()).populateStudents();
                    FrameController.getSmgp().setState("Group");
                    FrameController.changeFrameState("gg");
                    clear();
                    Start.d.editGroup(oldName, temp, locationTextField.getText(), true, FrameController.getGroup(groupNameTextField.getText()).getStudents());
    //            if(meetingIsHidden){
    //                toggleMeetingTab();
    //            }
                }else{
                    if(groupNameTextField.getText().toUpperCase().charAt(0)==groupNameTextField.getText().toLowerCase().charAt(0)){
                        javax.swing.JOptionPane.showMessageDialog(FrameController.getMf(), "The first character of the Group Name must be a letter. (A-Z, a-z)");
                        return;
                    }
                    Group temp=new Group(MiscUtils.getNextGroupIdentifier(groupNameTextField.getText()), groupNameTextField.getText(),new ArrayList<Meeting>(),new ArrayList<Student>(), locationTextField.getText(), true);
                    if(Start.d.addGroup(temp, locationTextField.getText(), true)){
                        FrameController.addGroup(temp);
                        FrameController.getGroup(groupNameTextField.getText()).populateStudents();
                        FrameController.getSmgp().setState("Group");
                        FrameController.changeFrameState("gg");
                        new Thread(new Runnable(){
                            @Override
                            public void run(){
                                String groupName=getGroupName();
                                clear();
                                Start.d.addStudents(groupName, FrameController.getGroup(groupName).getStudents());
                            }
                        }).start();
                    }else{
                        javax.swing.JOptionPane.showMessageDialog(FrameController.getMf(), groupNameTextField.getText()+" already exists!");
                    }
    //            if(meetingIsHidden){
    //                toggleMeetingTab();
    //            }
                }
            }else{
                javax.swing.JOptionPane.showMessageDialog(FrameController.getMf(), "Group Name must contain only Alphanumeric Characters! (A-Za-Z0-9) excludes \'-\'");
            }   
        }else{
            javax.swing.JOptionPane.showMessageDialog(FrameController.getMf(), "Group Name cannot be blank!");
        }
    }//GEN-LAST:event_createButtonMouseReleased

    private void cancelButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseReleased
        FrameController.changeFrameState("gg");
        clear();
//        if(meetingIsHidden){
//            toggleMeetingTab();
//        }
    }//GEN-LAST:event_cancelButtonMouseReleased

    private void browseButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_browseButtonMouseReleased
        locationTextField.setText(FrameController.chooseFile());
    }//GEN-LAST:event_browseButtonMouseReleased

    private void groupNameTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_groupNameTextFieldKeyReleased
        if(!groupNameTextField.getText().matches("[0-9a-zA-Z]+")){
            groupNameTextField.setBackground(Color.red);
        }else{
            groupNameTextField.setBackground(Color.GREEN);
        }
    }//GEN-LAST:event_groupNameTextFieldKeyReleased

    @Override
    public void clear(){
        groupNameTextField.setText("");
        locationTextField.setText("");
        groupNameTextField.setBackground(Color.RED);
//        mep.clear();
//        meetingTab.setSelectedIndex(0);
//        if(!meetingIsHidden){
//            mainTabbedPane.getComponent(1).repaint();
//        }
//        mainTabbedPane.setSelectedIndex(0);
    }
    
    public void putData(Group g){
        groupNameTextField.setText(g.getName());
        locationTextField.setText(g.getEPath());
        oldName=g.getName();
        if(!groupNameTextField.getText().matches("[0-9a-zA-Z]+")){
            groupNameTextField.setBackground(Color.red);
        }else{
            groupNameTextField.setBackground(Color.GREEN);
        }
    }

//    public void toggleMeetingTab(){
//        if(meetingIsHidden){
//            mainTabbedPane.addTab("Meeting", meetingTabPanel);
//        }else{
//            mainTabbedPane.removeTabAt(1);
//        }
//        meetingIsHidden=!meetingIsHidden;
//    }
    
    public String getGroupName(){
        return groupNameTextField.getText();
    }
    
    public void setIsEditing(boolean ie){
        isEditing=ie;
    }
    
    public void setCreateButtonText(String label) {
        createButton.setText(label);
    }
    
//    private javax.swing.JPanel meetingTabPanel;
//    private javax.swing.JTabbedPane meetingTab;
//    private MeetingEditPanel mep;
//    private boolean meetingIsHidden;
    private boolean isEditing;
    private String oldName;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton createButton;
    private javax.swing.JLabel groupNameLabel;
    private javax.swing.JTextField groupNameTextField;
    private javax.swing.JPanel groupTab;
    private javax.swing.JLabel importLabel;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JTextField locationTextField;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTabbedPane mainTabbedPane;
    // End of variables declaration//GEN-END:variables
}
