/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package attendease.gui;

import attendease.util.AutoDismiss;
import attendease.util.FrameController;
import attendease.util.Start;
import attendease.util.Student;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author timothy.chandler
 */
public class MeetingPanel extends javax.swing.JPanel {

    /**
     * Creates new form MeetingPanel
     */
    public MeetingPanel() {
        preInit();
        initComponents();
    }
    
    private void preInit(){
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            Start.createLog(ex, "Unable to set proper look and feel");
        }
        initTable();
    }

    private void initTable(){
        aTableModel=new DefaultTableModel();
        aTableModel.addColumn("Name");
        aTableModel.addColumn("Arrived at:");
        aTableModel.addColumn("Points");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sDLabel = new javax.swing.JLabel();
        sTLabel = new javax.swing.JLabel();
        mTLabel = new javax.swing.JLabel();
        doneButton = new javax.swing.JButton();
        idTextField = new javax.swing.JTextField();
        idTFLabel = new javax.swing.JLabel();
        attendanceTableScrollPane = new javax.swing.JScrollPane();
        attendanceTable = new javax.swing.JTable();

        sDLabel.setText("Date");

        sTLabel.setText("Time");

        mTLabel.setText("Title");

        doneButton.setText("Done");
        doneButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                doneButtonMouseReleased(evt);
            }
        });

        idTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idTextFieldKeyReleased(evt);
            }
        });

        idTFLabel.setText("Maually Enter ID Number");

        attendanceTable.setModel(aTableModel);
        attendanceTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        attendanceTable.setRowSelectionAllowed(false);
        attendanceTable.getTableHeader().setResizingAllowed(false);
        attendanceTable.getTableHeader().setReorderingAllowed(false);
        attendanceTableScrollPane.setViewportView(attendanceTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(attendanceTableScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idTFLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(198, 198, 198)
                        .addComponent(doneButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addComponent(sDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mTLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sTLabel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mTLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sTLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(attendanceTableScrollPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(idTFLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(doneButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void doneButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doneButtonMouseReleased
        FrameController.setCurrentPanel("emp");
    }//GEN-LAST:event_doneButtonMouseReleased

    private void idTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTextFieldKeyReleased
        if(evt.getKeyChar()=='\n'){
            ArrayList<Student> temp=stews;
            Collections.sort(stews, new Comparator<Student>(){
                @Override
                public int compare(Student s1, Student s2){
                    Integer i1=s1.getID();
                    Integer i2=s2.getID();
                    return i1.compareTo(i2);
                }
            });
            int id=0;
            try{
                id=new Integer(idTextField.getText());
                boolean found=false;
                while(!found&&temp.size()>1){
                    if(temp.get(temp.size()/2).getID()<id){
                        temp=(ArrayList)temp.subList(temp.size()/2, temp.size());
                    }else if(temp.get(temp.size()/2).getID()>id){
                        temp=(ArrayList)temp.subList(0,temp.size()/2);
                    }else{
                        found=true;
                    }
                }
                if(!found){
                    AutoDismiss.showMessageDialog(this, "You are not in this Group! Please check that you typed your ID number correctly");
                }else{
                    scanInStudent(temp.get(temp.size()/2));
                }
            }catch(NumberFormatException e){
                AutoDismiss.showMessageDialog(this, "That ID Number is Invalid!");
            }
        }
    }//GEN-LAST:event_idTextFieldKeyReleased

    private void scanInStudent(Student s){
        aTableModel.addRow(new Object[]{s.getName(),});
    }
    
    public void populateStudents(ArrayList<Student> ss){
        stews=ss;
    }
    
    public void setTitle(String title) {
        mTLabel.setText(title);
    }
    
    public void setStartDate(String date) {
        mTLabel.setText(date);
    }
    
    public void setStartTime(String time) {
        mTLabel.setText(time);
    }
    
    private DefaultTableModel aTableModel;
    private ArrayList<Student> stews;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable attendanceTable;
    private javax.swing.JScrollPane attendanceTableScrollPane;
    private javax.swing.JButton doneButton;
    private javax.swing.JLabel idTFLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel mTLabel;
    private javax.swing.JLabel sDLabel;
    private javax.swing.JLabel sTLabel;
    // End of variables declaration//GEN-END:variables
}
